# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/wrapper.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'protos/wrapper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import telemetry_pb2 as protos_dot_telemetry__pb2
from protos import command_pb2 as protos_dot_command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/wrapper.proto\x12\rstack.wrapper\x1a\x16protos/telemetry.proto\x1a\x14protos/command.proto\"\xb9\x01\n\x0eMessageWrapper\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x04\x12\x16\n\x0esource_service\x18\x02 \x01(\t\x12\x39\n\x08temp_tlm\x18\x03 \x01(\x0b\x32%.stack.telemetry.TemperatureTelemetryH\x00\x12\x33\n\tstate_cmd\x18\x04 \x01(\x0b\x32\x1e.stack.command.SetStateCommandH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.wrapper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEWRAPPER']._serialized_start=86
  _globals['_MESSAGEWRAPPER']._serialized_end=271
# @@protoc_insertion_point(module_scope)
