import time
from protos import telemetry_pb2
from protos import wrapper_pb2

def create_telemetry_payload(sensor_id, temperature):
    """
    Creates a serialized MessageWrapper containing TemperatureTelemetry.
    """
    # 1. Create the Telemetry message
    telemetry = telemetry_pb2.TemperatureTelemetry()
    telemetry.sensor_id = sensor_id
    telemetry.temperature_celsius = temperature

    # 2. Create the Wrapper message
    wrapper = wrapper_pb2.MessageWrapper()
    wrapper.timestamp_ms = int(time.time() * 1000)
    wrapper.source_service = "ds18b20_sensor"
    
    # 3. Populate the 'oneof' field in the wrapper
    # In protobuf, you assign fields of a oneof by accessing them directly on the message
    wrapper.temp_tlm.CopyFrom(telemetry)

    # 4. Serialize to bytes for MQTT transmission
    return wrapper.SerializeToString()

# Example usage/test:
if __name__ == "__main__":
    print("Testing payload creation...")
    payload = create_telemetry_payload("DS18B20_01", 25.5)
    print(f"Generated Bytes: {payload.hex()}")
    print("Payload ready for MQTT publish.")